### ISSUE TITLE
end tag uncorrectly set

### ISSUE THREAD

**Issue by jasonbillebault** [SublimeText/TJ3-syntax-sublimetext2#1]
Hello,

Can you change the project keyword from these tags !
```
		<dict>
			<key>begin</key>
			<string>project </string>
			<key>comment</key>
			<string>Project definition</string>
			<key>end</key>
			<string>\d{4}-\d{2}-\d{2} - \d{4}-\d{2}-\d{2} </string>
			<key>name</key>
			<string>storage.type.tj3</string>
		</dict>
```
to the tags :+1: 
```
		<dict>
			<key>begin</key>
			<string>project </string>
			<key>comment</key>
			<string>Project definition</string>
			<key>end</key>
			<string>{ </string>
			<key>name</key>
			<string>storage.type.tj3</string>
		</dict>
```

Your way of tagging the project keyword limit us to set a project to +4w or +4d by example.

Regards,
Jason.

**Comment by FichteFoll** [comment]
For someone unknown to this syntax, could you explain what effect this change will have? Are there any possibilities for regressions?

**Comment by jasonbillebault** [comment]
Hello, 

I think that this keyword isn't functionnal as weel.

here an example of the application of the keyword project from the fedora example project.

![image](https://user-images.githubusercontent.com/7589576/37597375-9ab23430-2b7f-11e8-84af-551433f7d776.png)

Unfortunately the \d{4}-\d{2}-\d{2} - \d{4}-\d{2}-\d{2} pattern doesn't appear.

The { char is mandatory, so it is the best way to stop the pattern in my opinion.
Otherwise we can replace \d{4}-\d{2}-\d{2} - \d{4}-\d{2}-\d{2} with this regex (not tried).

\d{4}-\d{2}-\d{2} (- \d{4}-\d{2}-\d{2}|\+\d{1,}(min|h|d|w|m|y))

https://regex101.com/r/UWdih9/1

**Comment by FichteFoll** [comment]
(oh wow, this syntax, looks terrible)

**Comment by jasonbillebault** [comment]
Haha, i'm just curious and for the moment the current syntax doesn't worth to continue existing. 
I think that the { character should be use as it is a mandatory character just after the project definition.
